#
# Copyright (C) 2025 Volt Active Data Inc.
#
# Use of this source code is governed by an MIT
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#

className: com.voltdb.tollcollect.pipeline.TollCollectStream

tps: 10000
voltdb:
  server: voltdb
